In [5]:
import numpy
import pandas as pd
 
def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    eij = R[i][j] - numpy.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])
                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])
        eR = numpy.dot(P,Q)
        e = 0
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] > 0:
                    e = e + pow(R[i][j] - numpy.dot(P[i,:],Q[:,j]), 2)
                    for k in range(K):
                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))
        if e < 0.001:
            break

    return P, Q.T

In [6]:
R = [
     [5,3,0,1],
     [5,3,0,1],
     [1,1,0,5],
     [1,0,0,4],
     [0,1,5,4],
    ]
R = numpy.array(R)
print(R)
N = len(R)
M = len(R[0])
K = 3
P = numpy.random.rand(N,K)
Q = numpy.random.rand(M,K)
print()
nP, nQ = matrix_factorization(R, P, Q, K)
#print(nP)
#print(nQ.T)
nR = numpy.dot(nP, nQ.T)
print(nR)



[[5 3 0 1]
 [5 3 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]]

[[4.97761481 2.98539765 3.15013959 0.99873315]
 [4.97729701 2.98788021 2.93751643 1.0003713 ]
 [1.02635246 0.94254163 5.57168144 4.96440369]
 [0.98841612 0.85151271 4.60585449 3.97582054]
 [1.34767306 1.06306373 4.95618188 4.01766602]]


In [7]:
R = pd.read_csv('history.csv')
cust_id=list(R['CUST_ID'][:10])
R=R.drop(['CUST_ID','CLV'],axis=1)
print(R)
R=R.head(10)
names = R.columns.values
R = numpy.array(R)
N = len(R)
M = len(R[0])
K = 100
P = numpy.random.rand(N,K)
Q = numpy.random.rand(M,K)
nP, nQ = matrix_factorization(R, P, Q, K)
nR = numpy.dot(nP, nQ.T)
df=pd.DataFrame(nR,index=cust_id,columns=names)
dff=df.apply(lambda row: row.sort_values(ascending=False).index, axis=1)
print(list(dff[1001]))
print(df)


    MONTH_1  MONTH_2  MONTH_3  MONTH_4  MONTH_5  MONTH_6
0       150       75      200      100      175       75
1        25       50      150      200      175      200
2        75      150        0       25       75       25
3       200      200       25      100       75      150
4       200      200      125       75      175      200
5        25      200      125      150       50       25
6       100      175      150      100       75       50
7       150       50       50       50       75      200
8       100      125      150       25      125       75
9       100       50      175       25      125      200
10       75       50        0      150       75      175
11      200      125       50      175      125      100
12       50      200       50      200       75        0
13      150      200       25      100       75      200
14      200      200      150      150      200      200
15      175      175      100       50      175       50
16      100      100      125  